replicaCount: 2

frontend:
  image:
    repository: <frontend-ecr-repo>
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80

backend:
  image:
    repository: <backend-ecr-repo>
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5000
