replicaCount: 2

image:
  repository: <your-dockerhub-username>/simple-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
