apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-app-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mern-app-frontend
  template:
    metadata:
      labels:
        app: mern-app-frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-app-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mern-app-backend
  template:
    metadata:
      labels:
        app: mern-app-backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        ports:
        - containerPort: 5000
