name: Build and Deploy to Kubernetes with ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the Ubuntu GitHub-hosted runner

    env:
      FRONTEND_IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/frontend-repo
      BACKEND_IMAGE_NAME: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend-repo
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      HELM_KUBE_NAMESPACE: default
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 3: Create ECR repositories if they don't exist
    - name: Create ECR repositories if they don't exist
      run: |
        aws ecr describe-repositories --repository-names frontend-repo || aws ecr create-repository --repository-name frontend-repo --region ${{ secrets.AWS_REGION }}
        aws ecr describe-repositories --repository-names backend-repo || aws ecr create-repository --repository-name backend-repo --region ${{ secrets.AWS_REGION }}

    # Step 4: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    # Step 5: Build and push Frontend Docker image
    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./frontend  # Build context for frontend (directory where Dockerfile is located)
        file: ./frontend/Dockerfile  # Path to the Dockerfile for frontend
        push: true
        tags: ${{ env.FRONTEND_IMAGE_NAME }}:latest

    # Step 6: Build and push Backend Docker image
    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./backend  # Build context for backend (adjust if needed)
        file: ./backend/Dockerfile  # Path to the Dockerfile for backend
        push: true
        tags: ${{ env.BACKEND_IMAGE_NAME }}:latest

    # Step 7: Set up Kubernetes Kubeconfig
    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

    # Step 8: Install Helm
    - name: Set up Helm
      uses: azure/setup-helm@v1

    # Step 9: Deploy to Kubernetes using Helm
    - name: Deploy to Kubernetes using Helm
      run: |
        helm upgrade --install my-frontend ./charts/frontend --namespace $HELM_KUBE_NAMESPACE --values ./charts/frontend/values.yaml --set image.repository=${{ env.FRONTEND_IMAGE_NAME }} --set image.tag=latest
        helm upgrade --install my-backend ./charts/backend --namespace $HELM_KUBE_NAMESPACE --values ./charts/backend/values.yaml --set image.repository=${{ env.BACKEND_IMAGE_NAME }} --set image.tag=latest
